name: burgher
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.0.0
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8+4
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
  flutter_secure_storage: ^8.1.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
